### ISSUE TITLE
Server side only routes/components?

### ISSUE THREAD

**Issue by dwjohnston** [rherwig/template-react-ssr#31]
I'm just getting started with this template - and am checking out the react-router feature branch. 

What I'm wondering with it - say I have some pages that are static, and are intended for indexing - 'About Us', 'Blog' etc. 

If I set that all up in the shared folder like you have done - and I navigate directly to the page then it renders on the serverside. 

However, I am at home first, and then I clicked a link to navigate to /About then the rendering happens on the client side. 

I'm just wondering about this unnecessarily increases the bundle size. ie. What if these static pages contain thousands of words. 

Is this a worthwhile concern, or should code splitting solve this anyway?

**Comment by rherwig** [comment]
This is a valid concern, since optimized apps only load and serve content, the user actually requests.
However, code splitting is exactly what is needed in that case.

I would general suggest, to chunk (code split) everything that is not needed for a specific route.
Either by using `import()` or react-universal-component.
When shipping a real-world project, however, you might want to go the extra mile and analyze, which pages are generally called by users and preload them. Webpack 4 offers the possibility to preload chunks in a non-blocking way.

Check out the docs in order to see, how this works:
https://webpack.js.org/guides/code-splitting/#prefetching-preloading-modules

And also let me know, if there are any further questions or suggestions on your side. :-)
