### ISSUE TITLE
How does this compare to nextjs?

### ISSUE THREAD

**Issue by dwjohnston** [rherwig/template-react-ssr#43]
NextJs is an out of the box SSR solution - supports code splitting, export to static website etc. 

How does this compare? Is there something that this is doing that nextjs doesn't? 

I haven't used NextJS - and for the most part, I've found this to a be a pretty clean and tidy solution.

**Comment by rherwig** [comment]
I used NextJS myself and found it to be really cool. This template started with the idea to provide a codebase that people can follow through in order to understand how universal rendering works and to keep it quite "vanilla" instead of using another framework stack.

For education and customization purposes I always find it useful to provide only the very barebone abstractions. But I see that opinions might be different on this one :-)

So the most basic difference would be: Next is a framework, this template is - well - a template.
